#!/bin/bash
# Master script to submit all codon optimization jobs
# Generated by batch_codon_optimizer.py
# Scheduler: PBS

cd /gpfs/home/sangiole/Github-repos/protein_design/LinearFoldMCOpt/batch_jobs

echo "Submitting 3 codon optimization jobs..."
echo ""

echo "Submitting job 1/3: luciferase_1BA3"
qsub /gpfs/home/sangiole/Github-repos/protein_design/LinearFoldMCOpt/batch_jobs/luciferase_1BA3/luciferase_1BA3.pbs
sleep 0.5  # Small delay between submissions

echo "Submitting job 2/3: gfp"
qsub /gpfs/home/sangiole/Github-repos/protein_design/LinearFoldMCOpt/batch_jobs/gfp/gfp.pbs
sleep 0.5  # Small delay between submissions

echo "Submitting job 3/3: test_nucleotide"
qsub /gpfs/home/sangiole/Github-repos/protein_design/LinearFoldMCOpt/batch_jobs/test_nucleotide/test_nucleotide.pbs
sleep 0.5  # Small delay between submissions


echo ""
echo "All 3 jobs submitted!"
echo "Monitor with: qstat -u $USER"
