#pragma once

#ifdef __cplusplus
extern "C" {
#endif

typedef enum {
    LP_STATUS_SUCCESS = 0,
    LP_STATUS_INVALID_ARGUMENT = 1,
    LP_STATUS_EXCEPTION = 2
} lp_status_t;

/**
 * Compute the ensemble free energy for the provided RNA sequence using
 * LinearPartition compiled in Vienna parameters mode.
 *
 * @param sequence        Null-terminated RNA sequence (will be upper-cased)
 * @param beamsize        Beam size parameter (>0). Defaults to 100 if <= 0.
 * @param no_sharp_turn   Non-zero to disallow sharp turns (default true).
 * @param verbose         Non-zero to enable verbose logging.
 * @param dangles         Dangle mode (default 2).
 * @param out_energy      Pointer that receives the ensemble free energy.
 * @return lp_status_t    0 on success, non-zero on error.
 */
int lp_compute_ensemble_energy(const char* sequence,
                               int beamsize,
                               int no_sharp_turn,
                               int verbose,
                               int dangles,
                               double* out_energy);

int lp_compute_bpp_matrix(const char* sequence,
                          int beamsize,
                          int no_sharp_turn,
                          int verbose,
                          int dangles,
                          double cutoff,
                          double* out_matrix,
                          long long out_matrix_len);

int lp_calculate_mea_structure(const char* sequence,
                               int beamsize,
                               int no_sharp_turn,
                               int verbose,
                               int dangles,
                               double gamma,
                               char* out_structure,
                               long long out_structure_len,
                               double* out_energy);

/**
 * Returns the last error string generated by the API. The returned pointer
 * remains valid until the next API call on the same thread.
 */
const char* lp_get_last_error(void);

#ifdef __cplusplus
}
#endif

